// =========================================
// GEORGE BOT ACTIVITIES
// Activity catalogue
// =========================================

const activities = [
    { title: "ScratchJr", description: "", icon: "🐱", category: "Computing Activities", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://codejr.org/" },
    { title: "Learn to Drag and Drop", description: "", icon: "🖱️", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/2/levels/1?viewAs=Instructor" },
    { title: "Sequencing with Scrat", description: "", icon: "🧩", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/4/levels/1" },
    { title: "Programming with Scrat", description: "", icon: "🐿️", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/5/levels/1" },
    { title: "Programming with Rey and BB-8", description: "", icon: "🤖", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/6/levels/1" },
    { title: "Loops with Scrat", description: "", icon: "🔁", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/8/levels/1?viewAs=Instructor" },
    { title: "Loops with Laurel", description: "", icon: "🌳", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/9/levels/1" },
    { title: "Ocean Scene with Loops", description: "", icon: "🌊", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/10/levels/1" },
    { title: "Mini-Project: On the Move with Play Lab", description: "", icon: "🎮", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/12/levels/1" },
    { title: "End of Course Project", description: "", icon: "🏆", category: "Coding", level: 1, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursea-2025/units/1/lessons/13/levels/1" },
    { title: "Sequencing with Angry Birds", description: "", icon: "🐦", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/3/levels/1?viewAs=Instructor" },
    { title: "Programming with Angry Birds", description: "", icon: "🐦", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/4/levels/1" },
    { title: "Programming with Harvester", description: "", icon: "🚜", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/5/levels/1" },
    { title: "Loops with Harvester", description: "", icon: "🔁", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/7/levels/1?viewAs=Instructor" },
    { title: "Loops with Laurel", description: "", icon: "🌳", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/8/levels/1" },
    { title: "Drawing Gardens with Loops", description: "", icon: "🌷", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/9/levels/1" },
    { title: "Mini-Project: A Royal Battle with Events", description: "", icon: "👑", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/12/levels/1" },
    { title: "End of Course Project", description: "", icon: "🏆", category: "Coding", level: 2, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/courseb-2025/units/1/lessons/13/levels/1" },
    { title: "Programming with Angry Birds", description: "", icon: "🐦", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/3/levels/1" },
    { title: "Debugging in Maze", description: "", icon: "🐞", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/4/levels/1" },
    { title: "Collecting Treasure with Laurel", description: "", icon: "💎", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/5/levels/1" },
    { title: "Creating Art with Code", description: "", icon: "🎨", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/6/levels/1" },
    { title: "Loops with Rey and BB-8", description: "", icon: "🔁", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/8/levels/1" },
    { title: "Harvesting Crops with Loops", description: "", icon: "🌾", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/9/levels/1" },
    { title: "Mini-Project: Sticker Art", description: "", icon: "⭐", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/10/levels/1?viewAs=Instructor" },
    { title: "Build a Flappy Game", description: "", icon: "🐦", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/12/levels/1" },
    { title: "Mini-Project: Chase Game", description: "", icon: "🏃", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/13/levels/1" },
    { title: "End of Course Project", description: "", icon: "🏆", category: "Coding", level: 3, yearGroups: ["years1-2"], type: "external", link: "https://studio.code.org/courses/coursec-2025/units/1/lessons/17/levels/1" },

    // Years 3–4, Level 1
    { title: "Introduction to Online Puzzles", description: "", icon: "🧩", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/3/levels/1" },
    { title: "Debugging with Laurel", description: "", icon: "🐞", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/4/levels/1" },
    { title: "Sequencing in Music Lab", description: "", icon: "🎵", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/5/levels/1" },
    { title: "Events in Music Lab", description: "", icon: "🎶", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/6/levels/1" },
    { title: "Events in Bounce", description: "", icon: "🏀", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/7/levels/1?viewAs=Instructor" },
    { title: "Build a Star Wars Game", description: "", icon: "🌟", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/8/levels/1" },
    { title: "Dance Party", description: "", icon: "💃", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/9/levels/1" },
    { title: "Loops in Ice Age", description: "", icon: "❄️", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/11/levels/1?viewAs=Instructor" },
    { title: "Drawing Shapes with Loops", description: "", icon: "🔷", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/12/levels/1" },
    { title: "Nested Loops in Maze", description: "", icon: "🔁", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/13/levels/1?viewAs=Instructor" },
    { title: "Looking Ahead with Minecraft", description: "", icon: "⛏️", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/15/levels/1?viewAs=Instructor" },
    { title: "If/Else with Bee", description: "", icon: "🐝", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/16/levels/1" },
    { title: "While Loops in Farmer", description: "", icon: "👩‍🌾", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/17/levels/1?viewAs=Instructor" },
    { title: "Until Loops in Maze", description: "", icon: "🌀", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/18/levels/1" },
    { title: "End of Course Project • Level 1", description: "", icon: "🏆", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/19/levels/1" },
    { title: "End of Course Project • Level 2", description: "", icon: "🏆", category: "Coding", level: 1, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursed-2025/units/1/lessons/19/levels/2" },

    // Years 3–4, Level 2
    { title: "Swimming Fish with Sprite Lab", description: "", icon: "🐟", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/3/levels/1" },
    { title: "Hello World", description: "", icon: "👋", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/4/levels/1" },
    { title: "Mini-Project: Career Journeys", description: "", icon: "🧭", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/5/levels/1" },
    { title: "Game Design", description: "", icon: "🎮", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/6/levels/1?viewAs=Instructor" },
    { title: "Variables as Score", description: "", icon: "🏆", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/7/levels/1?viewAs=Instructor" },
    { title: "Environment and Players", description: "", icon: "🌍", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/8/levels/1?viewAs=Instructor" },
    { title: "Game Jam Day 1: Create", description: "", icon: "🕹️", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/9/levels/1" },
    { title: "Functions in Music Lab", description: "", icon: "🎵", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/12/levels/1" },
    { title: "Functions in Minecraft", description: "", icon: "⛏️", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/13/levels/1" },
    { title: "Functions with Artist", description: "", icon: "🎨", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/14/levels/1" },
    { title: "Conditionals in Minecraft: Voyage Aquatic", description: "", icon: "🌊", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/15/levels/1" },
    { title: "Conditionals with the Farmer", description: "", icon: "👩‍🌾", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/16/levels/1?viewAs=Instructor" },
    { title: "End of Course Project • Level 1", description: "", icon: "🏆", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/19/levels/1" },
    { title: "End of Course Project • Level 2", description: "", icon: "🏆", category: "Coding", level: 2, yearGroups: ["years3-4"], type: "external", link: "https://studio.code.org/courses/coursee-2025/units/1/lessons/19/levels/2" },

    // Years 5–6, Level 1
    { title: "Introducing Sprite Lab", description: "", icon: "🧩", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/2/levels/1" },
    { title: "Making Sprites", description: "", icon: "🎭", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/3/levels/1" },
    { title: "Mini-Project: Career Journeys", description: "", icon: "🧭", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/4/levels/1" },
    { title: "Sprites in Action", description: "", icon: "🎬", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/5/levels/1" },
    { title: "Mini-Project: Virtual Pet", description: "", icon: "🐾", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/6/levels/1" },
    { title: "Text and Prompts", description: "", icon: "💬", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/8/levels/1" },
    { title: "Mini-Project: User Input Programs", description: "", icon: "⌨️", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/9/levels/1" },
    { title: "Lots of Sprites", description: "", icon: "👾", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/10/levels/1" },
    { title: "Counting with Variables", description: "", icon: "🔢", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/11/levels/1?viewAs=Instructor" },
    { title: "Mini-Project: Collector Game", description: "", icon: "🎯", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/12/levels/2?viewAs=Instructor" },
    { title: "Outbreak", description: "", icon: "🦠", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/14/levels/2" },
    { title: "AI For Oceans", description: "", icon: "🌊", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/15/levels/1" },
    { title: "End of Course Project", description: "", icon: "🏆", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/17/levels/1" },
    { title: "Create your project", description: "", icon: "✨", category: "Coding", level: 1, yearGroups: ["years5-6"], type: "external", link: "https://studio.code.org/courses/coursef-2025/units/1/lessons/17/levels/2" },

    { title: "Scratch", description: "", icon: "🐱", category: "Computing Activities", yearGroups: ["years3-4", "years5-6"], type: "external", link: "https://scratch.mit.edu/" },
    { title: "Pixel Art", description: "", icon: "🎨", category: "Create & Design", yearGroups: ["years1-2", "years3-4", "years5-6"], type: "external", link: "https://www.pixilart.com/draw?ref=home-page" }
];